name: Generate Dark Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: sayyedrabeeh
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=dark&color_snake=%23a855f7&color_dots=%23161b22,%23006d32,%2326a641,%2339d353,%23ebedf0
            dist/github-contribution-grid-snake.gif?palette=dark&color_snake=%23a855f7&color_dots=%23161b22,%23006d32,%2326a641,%2339d353,%23ebedf0

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
